### ISSUE TITLE
Need maps:  * COMET (slide 8) * NOA (slide 9) * CRLab (slide 12) * Final network (COMET+NOA+5hepos))

### ISSUE THREAD

**Issue by xanthospap** [DSOlab/dsopres#2]

**Comment by xanthospap** [comment]
Μητς το βάζω σε εσένα αυτό γιατί βασικά δοκιμάζω πώς γίνονται αυτές οι μαλακίες με τα issues.

**Comment by demanasta** [comment]
Γαμάνε αυτές οι μαλακίες που ανακάλυψες!!
Δες τους χάρτε ςπου πρόσθεσα και τους συζητάμε

**Comment by demanasta** [comment]
.. και συνεχίζω...
ξανάφτιαξα του χάρτες πρόσθεσα και το hepos... τα νούμερα..
comet 16
noanet 18
crlnet 10
hepos 11 (tτο γαμησα?!!!)
#----------------------------
συνολο 55  για το greece αυτά που είναι σίγουρα πλοταρισμένα!

uranus 88 (εδώ κάτι χάσαμε?)
HeposFull 99

---και μια παρατήρηση... πήγα να τρέξω το xelatex και παρατήρησα ότι στο tex τα link στις εικονες πηγαίνουν στο φάκελο /img/ στον οποίο όμως δεν υπάρχουν εικόνες!!!! πώς το έκανες!!!!

**Comment by xanthospap** [comment]
Ωραιος ρε Μητς. Δεν ξέρω πως έγινε αυτό. Εκανα κάτι link αλλά νόμιζα οτι απέτυχαν! Θα τα δω μια τελευταία και τα ξανασυζηταμε στο Switzerland.
